name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'infra/k8s/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/actions-doctl@v2
        with:
          token: ${{secretes.DIGITAL_OCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save <kubernetes_cluster_name>
      - run: kubectl apply -f infra/k8s
